### PR TITLE
hdfs-6874: Added GETFILEBLOCKLOCATIONS support to httpfs

### PR DESCRIPTION
**Pull request by narendra-altiscale**
Please check, review and merge. Please add additional reviewers as you see fit.
Thanks,
Narendra

### CODE REVIEW

**Comment by narendra-altiscale** [comment]
I have submitted the pull request.
https://github.com/Altiscale/hadoop/pull/63
Thanks,
Narendra

**Comment by jack-altiscale** [comment]
Hi @narendra-altiscale, there are a lot of spacing issues with this PR. Please don't change lines that don't require code change. This applies to removing whitespace, changing indents, etc.

**Review by jack-altiscale — CHANGES_REQUESTED** [review]
Please only edit lines that need to be changed

**Comment by narendra-altiscale** [comment]
Reopening this one. I thought closing  this PR and opening a new PR might help with the git commit history. With the "squash" commits option available in git,  new PR is not needed. Henceforth will be reverting back to this PR.

**Comment by narendra-altiscale** [comment]
@jack-altiscale  I have removed all the white spaces and kept only the necessary changes. Can you please check now? 
Thanks,
Narendra

**Comment by jack-altiscale** [comment]
Thanks for fixing the spacing/indents. Are the tests in BaseTestHttpFSWith passing for you? They are failing for me in your branch however work fine in branch-2.7.7-alti-rebase.

**Comment by jack-altiscale** [comment]
Let's bring this in and test it. Thanks @narendra-altiscale

**Pull request merged**
